#!/bin/bash

code=$1
echo $code
cp tests/example1.txt user_uploads/$code
mkdir user_data/$code

./prepare_copycat -c $code &> user_data/$code/prepare_copycat.log
./run_copycat -d -c $code &> user_data/$code/run_copycat.log &


