#!/bin/bash

set -xv
threads=1

while getopts ":j:" opt; do
  case $opt in
    j)
      echo "-a was triggered, Parameter: $OPTARG" >&2
      threads=$OPTARG
      echo $threads
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      exit 1
      ;;
  esac
done

timestamp=$(date +"%Y%m%d%H%M%S")
echo user_data/$timestamp

mkdir user_data/$timestamp

/data/schatz/software/bin/parallel -j $threads --dryrun ./deconvolve_clone D.txt user_data/$timestamp {1} ::: $(seq 2 4)